### ISSUE TITLE
[Feature Request] Better support for scale transformation

### ISSUE THREAD

**Issue by neebs12** [nothingislost/obsidian-hover-editor#129]
Hi, 

Im mainly querying about the snippet below. This is used for scaling down the window which pops up when one uses hover-preview. This works well enough with vanilla and also works for your plugin as well. My feature request is that this is natively supported within your plugin settings as an additional setting within the plugin's options - currently, it is just being used as a css snippet.

```css
.popover.hover-popover {
  /* makes the content smaller */
  transform: scale(0.85); 
  /* ... irrelevant rules */
}
/* source: https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/82 */
```

I think this is super powerful as the text within the window appears smaller and so you can see more information with a smaller window whenever one uses the hover-popover feature.

See effect below - its quite subtle but the window is smaller while conveying the same amount of info:
With `transform: scale(0.85)`
![image](https://user-images.githubusercontent.com/51255216/167312049-6fc3b38e-638c-4c61-b7c3-42d119475e8b.png)

Without `transform: scale`
![image](https://user-images.githubusercontent.com/51255216/167312171-fb1717e1-7855-43a9-a7d8-600402d73a94.png)

On a side note: I actually tried this css-snippet with your plugin a few months ago and it didn't work then. Now it seems to work just fine.
