### ISSUE TITLE
z-index issues with Quick Explorer

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#21]
Hover editors overlay menus, even when they're pinned, making QE's menus unreadable.  Ideally, QE's layer would sit between pinned and transient popups, such that new popups would overlay the menus, but the menus would overlay older popups.  Unfortunately there is no such z-index as hover-editor uses 30 and 31, and that means QE would need to use 30.5.  :wink:  (Also, hover-editor is using hardcoded layer numbers rather than the Obsidian-defined `layer` variables, which may cause other issues in the future.)

**Comment by nothingislost** [comment]
Hmm, menus are natively z-index 65 but it looks like you override QE to be 29? Would this suffice? This would leave z-index 31 available for elements that wanted to appear between inactive and new/active popovers.

```css
.popover.hover-popover.is-active {
  z-index: calc(var(--layer-popover) + 2 );
}

.popover.hover-popover.is-new {
  z-index: calc(var(--layer-popover) + 3 );
}
```

z-index for popovers is still a bit of a hack and I'm still considering better options. At one point I was leaving them all at 30 and just changing around the DOM ordering which worked well except for the fact that editor doesn't like getting moved around in the DOM and resets itself in a couple different ways when that happens.

**Comment by pjeby** [comment]
Hm.  This is more complicated than I thought.  The *only* popovers that should be over QE are the ones it creates.  Maybe what I should be doing instead of placing the menus under the popovers, is setting popovers opened by QE to be over the menu layer...

Ok, got it figured out: I've changed QE so that instead of shifting itself down in the hierarchy, it shifts popovers opened after it upward.  That is, I'm using:

```css
.menu.qe-popup-menu ~ .popover.hover-popover {
    z-index: var(--layer-menu);
}
```

So you don't need to change anything on your end, and this works fine with the builtin popovers as well.  I've rolled this change out in QE 0.1.14.
