### ISSUE TITLE
Change line height

### ISSUE THREAD

**Issue by huachuman** [nothingislost/obsidian-hover-editor#236]
Is there any way to change line height in the hover editor? 

Currently the line height is much taller than how it appears in the rest of my vault. I tried poking around with the element picker tool to see if I could isolate the selector but I can't seem to figure out how to change line height for the hover editor.

Why isn't there a setting for this?

**Comment by pjeby** [comment]
It looks like it's an issue with a change in how font sizes are specified in newer versions of Obsidian.  Try this CSS:

```css
.popover.hover-editor .markdown-preview-view {
    font-size: var(--font-text-size);
}
```

**Comment by huachuman** [comment]
Thanks, but that one doesn't seem to do anything, sadly.

**Comment by pjeby** [comment]
How about this:

```css
body .popover.hover-editor .markdown-preview-view {
    font-size: var(--font-text-size);
}
```
