### ISSUE TITLE
Images don't adhere to the 'initial popover' setting

### ISSUE THREAD

**Issue by Faeust** [nothingislost/obsidian-hover-editor#271]
I have a few images (png, jpg) in my files. When I hover over them, though, they don't open in small boxes like I specify in the Hover Editor settings, but as large/full images. I have to manually make the popover window smaller every single time. Is there a way to fix this, or otherwise adjust it?

**Comment by pjeby** [comment]
Sorry, what settings do you mean?  There is a setting to zoom an image to fit the viewport on click, but nothing to *shrink* images.  (Images and PDFs do not necessarily use the initial size; in particular, images default to a full-size view.)

If you want to disable auto-sizing for just-opened images and PDFs, you can use a CSS snippet to set a max-height and max-width for new popups, e.g.:

```css
.popover.hover-editor.is-new {
  max-height: 200px;  /* or whatever dimensions you want */
  max-width: 200px;
}
```

This may not produce exactly the results you'd prefer if you are viewing a lot of very-large images, as it will shrink the popup but will not reposition it.
