### ISSUE TITLE
FR: automatically determine hover view's width and height based on the content

### ISSUE THREAD

**Issue by shaopeng-ye** [nothingislost/obsidian-hover-editor#314]
Don’t set fixed dimensions for the hover view, improve it to automatically determine its width and height based on the content.

Similar to how the default hover view works in Obsidian.

```css
body {
    --popover-width: fit-content;
    --popover-height: fit-content;
}
.popover.hover-popover > .markdown-embed .markdown-source-view,
.popover.hover-popover .markdown-preview-view {
    min-width: 30vh;
    max-height: 60vh;
    background-color: #f4f5fb;
    font-size: calc(var(--font-text-size) * 0.9);
}

.popover.hover-popover .media-embed.image-embed.is-loaded {
    max-width: 85vh;
}
```

![Image](https://github.com/user-attachments/assets/584c6fb3-b31d-4748-b186-3fdd778dbb6e)
