### ISSUE TITLE
Support setting default hover editor size

### ISSUE THREAD

**Issue by wenlzhang** [nothingislost/obsidian-hover-editor#48]
Is it possible to support setting a default size for the hover editor? For instance, there can be an option to set a size in the configuration pane, with something like `x*y` for the default pop-up size. This can be very useful for longer notes.

**Comment by pjeby** [comment]
You can use CSS, like this:

```css
div.popover.hover-popover {
    width: 500px;
    min-height: 800px;
}
```

The above will also work with the core page preview plugin.
