### ISSUE TITLE
Allow replacing the "pin" icon

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#97]
Even after all this time, the pin angle thing is still hugely counterintuitive to me: I never remember which angle means what and so can't tell at a glance whether a popover is pinned.  (I tried setting the fill color in CSS, but lucide-pin has only a tiny fill area that's still pretty indistinguishable.)

So, I'd like to use the lucide-bookmark icon instead, with fill/unfilled as the distinction, because that makes it *really* obvious what's what.  But...  I can't figure out how to replace the icon using CSS, certainly not while keeping theme colors intact.  As far as I can tell the only way to change the icon is by changing HE's source, which I suppose I could maintain as a private fork, but it'd be nice if there were a way to make it work without doing that.

I'm assuming from previous discussion that you're not willing to make the bookmark the default icon, so it'd be nice to have the option to change it.  (I would, of course, be willing to write a PR for either option.)

**Comment by nothingislost** [comment]
How about this for now? I'm not against changing this to the default but let's see how it feels for a bit

```css
.hover-editor .popover-header-icon svg > path {
  display: none;
}
.hover-editor .popover-header-icon svg  {
  background-color: currentColor;
  transform: none;
  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z'%3E%3C/path%3E%3C/svg%3E");
}

.hover-editor .popover-header-icon.is-active svg  {
  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='17' height='17' viewBox='0 0 24 24' fill='currentColor' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z'%3E%3C/path%3E%3C/svg%3E");
}
```
